[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    '@yield-protocol/=./node_modules/@yield-protocol/'
]

# See more config options https://github.com/gakonst/foundry/tree/master/config